name: Auto-close TODO issues
on:
  push:
    branches: [master]
jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Auto-close TODO issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ruby << 'EOF'
            # TODO: #6 Automatically close issues with TODO label when corresponding TODO comment is gone
            todo_issues_in_code = `git grep 'TODO: #'`.scan(/TODO: #(\d+)/)
            p todo_issues_in_code

            # TODO: #7 Find the issues with the TODO label

            # TODO: #8 Close the unclosed issues with the TODO label but without corresponding TODO comment
          EOF
