name: Auto-close TODO issues
on:
  push:
    branches: [main]
jobs:
  auto_close:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Auto-close TODO issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ruby << 'EOF'
            require 'json'

            todo_issues_in_code = `git grep 'TODO: #'`.scan(/TODO: #(\d+)/).map { |a| a[0].to_i }
            puts "TODO markers found in code:"
            p todo_issues_in_code

            open_issues_with_todo_label = JSON.parse `curl "https://api.github.com/repos/$GITHUB_REPOSITORY/issues?per_page=100&labels=TODO&access_token=$GITHUB_TOKEN"`
            puts "Open issues with TODO label:"
            p open_issues_with_todo_label.map { |issue| issue['number'] }

            open_issues_with_todo_label.each do |issue|
              next if todo_issues_in_code.include? issue['number']
              puts "Closing issue ##{issue['number']}"
              message = [
                "I am closing this issue now because these two conditions are met:",
                "",
                "- This issue has a `TODO` label.",
                "- A `TODO` comment referencing this issue no longer appears in the repository's default branch.",
                "",
                "The commit being processed is #{ENV['GITHUB_SHA']}. [Ran on GitHub Actions.](https://github.com/#{ENV['GITHUB_REPOSITORY']}/actions/runs/#{ENV['GITHUB_RUN_ID']})",
              ].join("\n")
              post_body = { body: message }
              system %(curl -X POST -H "Content-Type: application/json" -d@- "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/#{issue['number']}/comments?access_token=$GITHUB_TOKEN" << 'JSON'\n#{post_body.to_json}\nJSON)
              system %(echo '{"state":"closed"}' | curl -X PATCH -H "Content-Type: application/json" -d@- "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/#{issue['number']}?access_token=$GITHUB_TOKEN")
            end
          EOF
