name: Auto-close TODO issues
on:
  push:
    branches: [main]
jobs:
  auto_close:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Auto-close TODO issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ruby << 'EOF'
            require 'json'

            # TODO: #6 Automatically close issues with TODO label when corresponding TODO comment is gone
            todo_issues_in_code = `git grep 'TODO: #'`.scan(/TODO: #(\d+)/).map { |a| a[0].to_i }
            puts "TODO markers found in code:"
            p todo_issues_in_code

            open_issues_with_todo_label = JSON.parse `curl "https://api.github.com/repos/$GITHUB_REPOSITORY/issues?per_page=100&labels=TODO&access_token=$GITHUB_TOKEN"`
            puts "Open issues with TODO label:"
            p open_issues_with_todo_label.map { |issue| issue['number'] }

            open_issues_with_todo_label.each do |issue|
              continue if todo_issues_in_code.include? issue['number']
              # TODO: #8 Close the unclosed issues with the TODO label but without corresponding TODO comment
              puts "Closing issue ##{issue['number']}"
              # system %(curl -X PATCH -d state=closed "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/#{issue['number']}?access_token=$GITHUB_TOKEN")
              body = { body: "This issue would be closed" }
              system %(curl -X POST -H "Content-Type: application/json" -d@- "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/#{issue['number']}?access_token=$GITHUB_TOKEN" << 'JSON'\n#{body.to_json}\nJSON)
            end
          EOF
